#!/bin/bash
# specify the path to the slugs binary
slugs="/home/tung/Desktop/slugs/src/slugs"
# specify the path to the compiler for the structured slugs parser
parse_slugs="/home/tung/Desktop/slugs/tools/StructuredSlugsParser/compiler.py"
# define current directory
dir=$(pwd)
# define contract input directory
input=$dir/AG_contract


if [ $# -gt 0 ]; then
	if [ $1 = "check" ]; then
		start=$(date +%s%N)
		$parse_slugs $input.structuredslugs > $input.slugsin
		$slugs --explicitStrategy $input.slugsin > $input.strat
		end=$(date +%s%N)
		runtime=$((end-start))
		echo "Computed in $(($runtime/1000000000)) seconds"
        else
		python3 $dir/helpers/strategy_parser.py $input
                python3 $dir/scenarios/three_islands.py $input $1
	fi
else
		python3 $dir/helpers/strategy_parser.py $input
                python3 $dir/scenarios/three_islands.py $input 200
fi
